Cleaned up build process

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright (c) 2017 Martin Donath <martin.donath@squidfunk.com>
 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
@@ -18,6 +20,15 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
-# Configuration files are written in ES5 for compatibility
-karma.conf.js
-webpack.config.js
+# Exit, if one command fails
+set -e
+
+# Check if "yarn install" was executed
+if [[ ! -d "$(yarn bin)" ]]; then
+  echo "\"node_modules\" not found:"
+  echo "yarn install"
+  exit 1
+fi
+
+# Start test runner
+"$(yarn bin)"/karma start --single-run
diff --git a/scripts/watch b/scripts/watch
--- a/scripts/watch
+++ b/scripts/watch
@@ -20,10 +20,13 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
-# Check if "yarn" was executed
+# Exit, if one command fails
+set -e
+
+# Check if "yarn install" was executed
 if [[ ! -d "$(yarn bin)" ]]; then
   echo "\"node_modules\" not found:"
-  echo "yarn"
+  echo "yarn install"
   exit 1
 fi
 
